#ifndef FILESYSTEM_H
#define FILESYSTEM_H

#include <string>
#include <cstdlib>
#include "root_directory.h" // This is a configuration file generated by CMake.

// Apple-specific code to find the Resources directory in a .app bundle
#if defined(__APPLE__)
#include <CoreFoundation/CoreFoundation.h>
#endif

class FileSystem
{
private:
  typedef std::string (*Builder) (const std::string& path);

public:
  static std::string getPath(const std::string& path)
  {
    static std::string(*pathBuilder)(std::string const &) = getPathBuilder();
    return (*pathBuilder)(path);
  }

private:
  // This function is new. It uses CoreFoundation to get the bundle's resource path.
#if defined(__APPLE__)
  static std::string getPathForMac(const std::string& path) {
      CFBundleRef mainBundle = CFBundleGetMainBundle();
      CFURLRef resourcesURL = CFBundleCopyResourcesDirectoryURL(mainBundle);
      char buffer[PATH_MAX];
      if (!CFURLGetFileSystemRepresentation(resourcesURL, TRUE, (UInt8 *)buffer, PATH_MAX)) {
          // Error: Could not get path
          return "";
      }
      CFRelease(resourcesURL);

      return std::string(buffer) + "/" + path;
  }
#endif

  static std::string const & getRoot()
  {
    static char const * envRoot = getenv("LOGL_ROOT_PATH");
    static char const * givenRoot = (envRoot != nullptr ? envRoot : logl_root);
    static std::string root = (givenRoot != nullptr ? givenRoot : "");
    return root;
  }

  static Builder getPathBuilder()
  {
    if (getRoot() != "") {
      return &FileSystem::getPathRelativeRoot;
    }
#if defined(__APPLE__)
    // If on macOS and not using a root path, use the bundle resource path.
    return &FileSystem::getPathForMac;
#else
    // Fallback for other platforms like Windows/Linux
    return &FileSystem::getPathRelativeBinary;
#endif
  }

  static std::string getPathRelativeRoot(const std::string& path)
  {
    return getRoot() + std::string("/") + path;
  }

  static std::string getPathRelativeBinary(const std::string& path)
  {
    return "../../../" + path;
  }
};

// FILESYSTEM_H
#endif
